eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://39.107.242.71:3346/cold_user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123456

          initial-size: 10
          max-active: 100
          min-idle: 10
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
          filter:
              stat:
                  log-slow-sql: true
                  slow-sql-millis: 1000
                  merge-sql: false
              wall:
                  config:
                      multi-statement-allow: true
# 线程池配置
thread:
    pool:
        coreSize: 5
        maxSize: 10
        queueCapacity: 1000

# 票务配置
ticket:
    presale:
        count: 100
    regular:
        count: 200
    lastMinute:
        count: 50